import { RootStyleRegistry } from "@/library/RootStyleRegistry";
import { ConfigProvider } from "antd";
import { Open_Sans } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
export const open_sans = Open_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Zadez Simple",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "/Logo-ZADEZ.png",
      type: "image/png",
    },
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={open_sans.className}>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "#AF131C",
            },
          }}
        >
          <RootStyleRegistry>{children}</RootStyleRegistry>
        </ConfigProvider>
      </body>
    </html>
  );
}
